#!/usr/bin/python3
""" module containing a class
execute: ./9-main.py
"""


class Student:
    """ student class """

    def __init__(self, first_name, last_name, age):
        self.first_name = first_name
        self.last_name = last_name
        self.age = age

    """ method to return dict representation of class instance """
    def to_json(self):
        """return attrs is attrs is a list of strings else return all """
        if (type(attrs) == list and
            all(type(memeber) == str for member in attrs):
            return {l: getattr(self, l) for l in attrs if hasattr(self, l)}
        return self.__dict__
